version: "3.8"
services:
  dynamodb:
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data -port 9000"
    working_dir: /home/dynamodblocal
    image: amazon/dynamodb-local:2.1.0
    volumes:
      - dynamodb-data:/data
    network_mode: host
  ranklab-test:
    image: ranklab-test:latest
    network_mode: host
    environment:
      - NODE_ENV=test
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:3000/api/health"]
      interval: 3s
      timeout: 30s
      retries: 10
  ranklab-api:
    image: ghcr.io/ranklab-gaming/ranklab-api:latest
    network_mode: host
    environment:
      - ROCKET_PROFILE=test
      - RANKLAB_AWS_ACCESS_KEY_ID
      - RANKLAB_AWS_SECRET_KEY
      - RANKLAB_AVATAR_PROCESSOR_LAMBDA_ARN
      - RANKLAB_MEDIA_CONVERT_QUEUE_ARN
      - RANKLAB_MEDIA_CONVERT_ROLE_ARN
      - RANKLAB_REKOGNITION_QUEUE_URL
      - RANKLAB_REKOGNITION_ROLE_ARN
      - RANKLAB_REKOGNITION_TOPIC_ARN
      - RANKLAB_UPLOADS_BUCKET
      - RANKLAB_UPLOADS_QUEUE_URL
      - RANKLAB_SENTRY_DSN
      - RANKLAB_INSTANCE_ID
    depends_on:
      ranklab-test:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "httpx://localhost:8000/"]
      interval: 3s
      timeout: 30s
      retries: 10
volumes:
  dynamodb-data:
