version: "3.8"
services:
  dynamodb:
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data -port 9000"
    working_dir: /home/dynamodblocal
    image: amazon/dynamodb-local:latest
    volumes:
      - dynamodb-data:/data
    network_mode: host
  ranklab-test:
    image: ranklab-test:latest
    network_mode: host
    environment:
      - NODE_ENV=test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 3s
      timeout: 30s
      retries: 10
  ranklab-api:
    image: ghcr.io/ranklab-gaming/ranklab-api:latest
    network_mode: host
    environment:
      - ROCKET_PROFILE=test
      - RANKLAB_AWS_ACCESS_KEY_ID
      - RANKLAB_AWS_SECRET_KEY
      - RANKLAB_S3_BUCKET_QUEUE
      - RANKLAB_S3_BUCKET
      - RANKLAB_SENTRY_DSN
      - RANKLAB_STRIPE_CONNECT_WEBHOOKS_QUEUE
      - RANKLAB_STRIPE_CONNECT_WEBHOOKS_SECRET
      - RANKLAB_STRIPE_DIRECT_WEBHOOKS_QUEUE
      - RANKLAB_STRIPE_DIRECT_WEBHOOKS_SECRET
      - RANKLAB_STRIPE_SECRET
      - RANKLAB_INSTANCE_ID
    depends_on:
      ranklab-test:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 3s
      timeout: 30s
      retries: 10
