/* tslint:disable */
/* eslint-disable */
/**
 * ranklab-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Coach
 */
export interface Coach {
    /**
     * 
     * @type {string}
     * @memberof Coach
     */
    bio: string;
    /**
     * 
     * @type {string}
     * @memberof Coach
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Coach
     */
    gameId: string;
    /**
     * 
     * @type {string}
     * @memberof Coach
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Coach
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Coach
     */
    userId: string;
}

export function CoachFromJSON(json: any): Coach {
    return CoachFromJSONTyped(json, false);
}

export function CoachFromJSONTyped(json: any, ignoreDiscriminator: boolean): Coach {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bio': json['bio'],
        'email': json['email'],
        'gameId': json['game_id'],
        'id': json['id'],
        'name': json['name'],
        'userId': json['user_id'],
    };
}

export function CoachToJSON(value?: Coach | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bio': value.bio,
        'email': value.email,
        'game_id': value.gameId,
        'id': value.id,
        'name': value.name,
        'user_id': value.userId,
    };
}


