/* tslint:disable */
/* eslint-disable */
/**
 * ranklab-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCoachRequest
 */
export interface CreateCoachRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCoachRequest
     */
    bio: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCoachRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCoachRequest
     */
    gameId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCoachRequest
     */
    name: string;
}

export function CreateCoachRequestFromJSON(json: any): CreateCoachRequest {
    return CreateCoachRequestFromJSONTyped(json, false);
}

export function CreateCoachRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCoachRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bio': json['bio'],
        'email': json['email'],
        'gameId': json['game_id'],
        'name': json['name'],
    };
}

export function CreateCoachRequestToJSON(value?: CreateCoachRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bio': value.bio,
        'email': value.email,
        'game_id': value.gameId,
        'name': value.name,
    };
}


