version: "3"
services:
  ranklab-web:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      ranklab:
        aliases:
          - ranklab-test
    extra_hosts:
      ranklab-test: 0.0.0.0
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
networks:
  ranklab:
    name: ranklab
