version: "3"
services:
  ranklab-web:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - ranklab
    extra_hosts:
      ranklab-api: 0.0.0.0
      ranklab-development: 0.0.0.0
networks:
  ranklab:
    name: ranklab
