version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - ranklab
  ranklab-web:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      ranklab:
        aliases:
          - ranklab-test
    extra_hosts:
      ranklab-test: 0.0.0.0
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
      - DISPLAY
    depends_on:
      - redis
volumes:
  redis:
networks:
  ranklab:
    name: ranklab
