version: "3"
services:
  dynamodb:
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data -port 9000"
    working_dir: /home/dynamodblocal
    image: amazon/dynamodb-local:2
    ports:
      - "9000:9000"
    volumes:
      - dynamodb-data:/data
    networks:
      - ranklab
  ranklab-web:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      ranklab:
        aliases:
          - ranklab-test
    extra_hosts:
      ranklab-test: 0.0.0.0
    environment:
      - DISPLAY
    depends_on:
      - dynamodb
volumes:
  dynamodb-data:
networks:
  ranklab:
    name: ranklab
