version: "3"
services:
  ranklab-web:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - ranklab
networks:
  ranklab:
    name: ranklab
