/**
 * ranklab-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("getHealth", () => {
    return expect(instance.getHealth({})).resolves.toBe(null)
  })
})

describe("RanklabApi", () => {
  let instance: api.RanklabApi
  beforeEach(function() {
    instance = new api.RanklabApi(config)
  });

  test("coachesCreate", () => {
    const body: api.CreateCoachRequest = undefined
    return expect(instance.coachesCreate(body, {})).resolves.toBe(null)
  })
  test("commentsCreate", () => {
    const body: api.CreateCommentRequest = undefined
    return expect(instance.commentsCreate(body, {})).resolves.toBe(null)
  })
  test("recordingsCreate", () => {
    return expect(instance.recordingsCreate({})).resolves.toBe(null)
  })
  test("reviewsCreate", () => {
    const body: api.CreateReviewRequest = undefined
    return expect(instance.reviewsCreate(body, {})).resolves.toBe(null)
  })
  test("reviewsGet", () => {
    const id: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.reviewsGet(id, {})).resolves.toBe(null)
  })
  test("reviewsList", () => {
    return expect(instance.reviewsList({})).resolves.toBe(null)
  })
  test("usersGetCurrent", () => {
    return expect(instance.usersGetCurrent({})).resolves.toBe(null)
  })
})

