version: "3"
services:
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_test
    ports:
      - "5432:5432"
  migration:
    image: ${AWS_CONTAINER_REGISTRY_SERVER}/ranklab-api-production:latest
    command:
      - ./bin/test-prepare
  ranklab-api:
    image: ${AWS_CONTAINER_REGISTRY_SERVER}/ranklab-api-production:latest
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/app_test
      - ROCKET_ADDRESS=0.0.0.0
      - RANKLAB_AUTH0_DOMAIN=https://ranklab-development.eu.auth0.com/
      - RANKLAB_S3_BUCKET=ranklab-dev
      - RANKLAB_AWS_ACCESS_KEY_ID
      - RANKLAB_AWS_SECRET_KEY
    ports:
      - "8000:8000"
    depends_on:
      - migration
