name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache builds
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/packages/ranklab-web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-${{ hashFiles('packages/**/*.[jt]sx?') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          build: yarn build
          start: docker-compose -f docker-compose.cypress.yml up, yarn start
          working-directory: packages/ranklab-web
        env:
          NODE_ENV: test
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          AWS_CONTAINER_REGISTRY_SERVER: ${{ secrets.AWS_CONTAINER_REGISTRY_SERVER }}
          API_HOST: http://localhost:8000
          AUTH0_BASE_URL: http://localhost:3000
          NODE_OPTIONS: "--max_old_space_size=4096"
