name: End-to-end tests
on: [push]

env:
  NODE_ENV: test
  NODE_OPTIONS: --max_old_space_size=4096
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app_test
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/base:14.17.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/packages/ranklab-web/.next/cache
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install
      - run: yarn build
      - run: tar -czf /tmp/ranklab-web.tar.gz .
      - name: Save project folder
        uses: actions/upload-artifact@v2
        with:
          name: ranklab-web.tar.gz
          if-no-files-found: error
          path: /tmp/ranklab-web.tar.gz
          retention-days: 1
  chrome-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: install
    container:
      image: cypress/included:8.7.0
      options: --add-host=ranklab-test.gg:0.0.0.0
      volumes:
        - /var/lib/docker/containers:/containers
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
      ranklab-api:
        env:
          ROCKET_PROFILE: test
          ROCKET_LOG_LEVEL: debug
          ROCKET_ADDRESS: 0.0.0.0
          RANKLAB_AUTH0_DOMAIN: https://ranklab-development.eu.auth0.com/
          RANKLAB_S3_BUCKET: ${{ secrets.RANKLAB_S3_BUCKET }}
          RANKLAB_AWS_ACCESS_KEY_ID: ${{ secrets.RANKLAB_AWS_ACCESS_KEY_ID }}
          RANKLAB_AWS_SECRET_KEY: ${{ secrets.RANKLAB_AWS_SECRET_KEY }}
        image: ghcr.io/ranklab-gaming/ranklab-api:latest
        credentials:
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PASSWORD }}
    steps:
      - name: Download the project folder
        uses: actions/download-artifact@v2
        with:
          name: ranklab-web.tar.gz
      - run: tar -xzf ranklab-web.tar.gz
      - name: Chrome tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: packages/ranklab-web
          record: true
          start: yarn test:start
          wait-on: "http://ranklab-api:8000,http://ranklab-test.gg:3000"
          browser: chrome
          group: "Chrome"
          install: false
      - name: Log server logs
        if: ${{ failure() }}
        run: cat /containers/**/*.log

  chrome-mobile-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: install
    container:
      image: cypress/included:8.7.0
      options: --add-host=ranklab-test.gg:0.0.0.0
      volumes:
        - /var/lib/docker/containers:/containers
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
      ranklab-api:
        env:
          ROCKET_PROFILE: test
          ROCKET_LOG_LEVEL: debug
          ROCKET_ADDRESS: 0.0.0.0
          RANKLAB_AUTH0_DOMAIN: https://ranklab-development.eu.auth0.com/
          RANKLAB_S3_BUCKET: ${{ secrets.RANKLAB_S3_BUCKET }}
          RANKLAB_AWS_ACCESS_KEY_ID: ${{ secrets.RANKLAB_AWS_ACCESS_KEY_ID }}
          RANKLAB_AWS_SECRET_KEY: ${{ secrets.RANKLAB_AWS_SECRET_KEY }}
        image: ghcr.io/ranklab-gaming/ranklab-api:latest
        credentials:
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PASSWORD }}
    steps:
      - name: Download the project folder
        uses: actions/download-artifact@v2
        with:
          name: ranklab-web.tar.gz
      - run: tar -xzf ranklab-web.tar.gz
      - name: Chrome tests
        uses: cypress-io/github-action@v2
        with:
          config: "viewportWidth=375,viewportHeight=667"
          working-directory: packages/ranklab-web
          record: true
          start: yarn test:start
          wait-on: "http://ranklab-api:8000,http://ranklab-test.gg:3000"
          browser: chrome
          group: "Chrome - Mobile"
          install: false
      - name: Log server logs
        if: ${{ failure() }}
        run: cat /containers/**/*.log

  firefox-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: install
    container:
      image: cypress/included:8.7.0
      options: >-
        --user 1001
        --add-host=ranklab-test.gg:0.0.0.0
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
      ranklab-api:
        env:
          ROCKET_PROFILE: test
          ROCKET_ADDRESS: 0.0.0.0
          RANKLAB_AUTH0_DOMAIN: https://ranklab-development.eu.auth0.com/
          RANKLAB_S3_BUCKET: ${{ secrets.RANKLAB_S3_BUCKET }}
          RANKLAB_AWS_ACCESS_KEY_ID: ${{ secrets.RANKLAB_AWS_ACCESS_KEY_ID }}
          RANKLAB_AWS_SECRET_KEY: ${{ secrets.RANKLAB_AWS_SECRET_KEY }}
        image: ghcr.io/ranklab-gaming/ranklab-api:latest
        credentials:
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PASSWORD }}
    steps:
      - name: Download the project folder
        uses: actions/download-artifact@v2
        with:
          name: ranklab-web.tar.gz
      - run: tar -xzf ranklab-web.tar.gz
      - name: Firefox tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: packages/ranklab-web
          record: true
          start: yarn test:start
          wait-on: "http://ranklab-api:8000,http://ranklab-test.gg:3000"
          browser: firefox
          group: "Firefox"
          install: false
      - name: Log server logs
        if: ${{ failure() }}
        run: cat /containers/**/*.log

  firefox-mobile-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: install
    container:
      image: cypress/included:8.7.0
      options: >-
        --user 1001
        --add-host=ranklab-test.gg:0.0.0.0
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
      ranklab-api:
        env:
          ROCKET_PROFILE: test
          ROCKET_ADDRESS: 0.0.0.0
          RANKLAB_AUTH0_DOMAIN: https://ranklab-development.eu.auth0.com/
          RANKLAB_S3_BUCKET: ${{ secrets.RANKLAB_S3_BUCKET }}
          RANKLAB_AWS_ACCESS_KEY_ID: ${{ secrets.RANKLAB_AWS_ACCESS_KEY_ID }}
          RANKLAB_AWS_SECRET_KEY: ${{ secrets.RANKLAB_AWS_SECRET_KEY }}
        image: ghcr.io/ranklab-gaming/ranklab-api:latest
        credentials:
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PASSWORD }}
    steps:
      - name: Download the project folder
        uses: actions/download-artifact@v2
        with:
          name: ranklab-web.tar.gz
      - run: tar -xzf ranklab-web.tar.gz
      - name: Firefox tests
        uses: cypress-io/github-action@v2
        with:
          config: "viewportWidth=375,viewportHeight=667"
          working-directory: packages/ranklab-web
          record: true
          start: yarn test:start
          wait-on: "http://ranklab-api:8000,http://ranklab-test.gg:3000"
          browser: firefox
          group: "Firefox - Mobile"
          install: false
      - name: Log server logs
        if: ${{ failure() }}
        run: cat /containers/**/*.log
