name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "0.0.0.0 ranklab-api" | sudo tee -a /etc/hosts
          sudo echo "0.0.0.0 ranklab-development" | sudo tee -a /etc/hosts
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CONTAINER_REGISTRY_USER }}
          aws-secret-access-key: ${{ secrets.AWS_CONTAINER_REGISTRY_PASSWORD }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache builds
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/packages/ranklab-web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: packages/ranklab-web
          command: yarn ci:run
        env:
          NODE_ENV: test
          NODE_OPTIONS: --max_old_space_size=4096
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          AWS_CONTAINER_REGISTRY_SERVER: ${{ secrets.AWS_CONTAINER_REGISTRY_SERVER }}
          RANKLAB_AWS_ACCESS_KEY_ID: ${{ secrets.RANKLAB_AWS_ACCESS_KEY_ID }}
          RANKLAB_AWS_SECRET_KEY: ${{ secrets.RANKLAB_AWS_SECRET_KEY }}
          CYPRESS_auth0ClientSecret: ${{ secrets.CYPRESS_AUTH0CLIENTSECRET }}
          CYPRESS_auth0CookieSecret: ${{ secrets.CYPRESS_AUTH0COOKIESECRET }}
