name: End-to-end tests
on: [push]
env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/app_test
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
  RANKLAB_AWS_ACCESS_KEY_ID: ${{ secrets.RANKLAB_AWS_ACCESS_KEY_ID }}
  RANKLAB_AWS_SECRET_KEY: ${{ secrets.RANKLAB_AWS_SECRET_KEY }}
  CYPRESS_auth0ClientSecret: ${{ secrets.CYPRESS_AUTH0CLIENTSECRET }}
  CYPRESS_auth0CookieSecret: ${{ secrets.CYPRESS_AUTH0COOKIESECRET }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache builds
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/packages/ranklab-web/.next/cache
          key: ${{ runner.os }}-nextjs-build-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-build-cache-
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - name: Build docker container
        run: DOCKER_BUILDKIT=1 docker build -f ${{ github.workspace }}/packages/ranklab-web/cypress/Dockerfile -t ranklab-web . && docker save -o ${{ github.workspace }}/ranklab-web.tar ranklab-web
      - name: Save docker container
        uses: actions/upload-artifact@v2
        with:
          name: ranklab-web.tar
          if-no-files-found: error
          path: ${{ github.workspace }}/ranklab-web.tar
  ui-chrome-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: install
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Add hosts to /etc/hosts
        run: |
          echo "0.0.0.0 ranklab-api" | tee -a /etc/hosts
          echo "0.0.0.0 ranklab-development" | tee -a /etc/hosts
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download the docker container
        uses: actions/download-artifact@v2
        with:
          name: ranklab-web.tar
      - run: docker load -i ranklab-web.tar
      - run: yarn global add start-server-and-test
      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: packages/ranklab-web
          command: yarn ci:run
        env:
          BROWSER: chrome
          GROUP: UI - Chrome
  ui-firefox-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: install
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Add hosts to /etc/hosts
        run: |
          echo "0.0.0.0 ranklab-api" | tee -a /etc/hosts
          echo "0.0.0.0 ranklab-development" | tee -a /etc/hosts
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download the docker container
        uses: actions/download-artifact@v2
        with:
          name: ranklab-web.tar
      - run: docker load -i ranklab-web.tar
      - run: yarn global add start-server-and-test
      - name: "UI Tests - Firefox"
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: packages/ranklab-web
          command: yarn ci:run
        env:
          BROWSER: firefox
          GROUP: UI - Firefox
