name: End-to-end tests
on: [push]

env:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app_test
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
  CYPRESS_auth0ClientSecret: ${{ secrets.CYPRESS_AUTH0CLIENTSECRET }}
  CYPRESS_auth0CookieSecret: ${{ secrets.CYPRESS_AUTH0COOKIESECRET }}

jobs:
  ui-chrome-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: cypress/browsers:node14.17.0-chrome91-ff89
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
      ranklab-api:
        env:
          ROCKET_ADDRESS: 0.0.0.0
          RANKLAB_AUTH0_DOMAIN: https://ranklab-development.eu.auth0.com/
          RANKLAB_S3_BUCKET: ranklab-dev
          RANKLAB_AWS_ACCESS_KEY_ID: ${{ secrets.RANKLAB_AWS_ACCESS_KEY_ID }}
          RANKLAB_AWS_SECRET_KEY: ${{ secrets.RANKLAB_AWS_SECRET_KEY }}
        image: ghcr.io/ranklab-gaming/ranklab-api:latest
        credentials:
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache builds
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/packages/ranklab-web/.next/cache
          key: ${{ runner.os }}-nextjs-build-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-build-cache-
      - name: Add hosts to /etc/hosts
        run: echo "0.0.0.0 ranklab-development" | tee -a /etc/hosts
      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          working-directory: packages/ranklab-web
          record: true
          build: yarn build
          start: yarn start
          wait-on: "http://ranklab-api:8000,http://ranklab-web:3000"
          browser: chrome
          group: "UI - Chrome"
        env:
          NODE_ENV: test
  ui-firefox-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: cypress/browsers:node14.17.0-chrome91-ff89
      options: --user 1001
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
      ranklab-api:
        env:
          ROCKET_ADDRESS: 0.0.0.0
          RANKLAB_AUTH0_DOMAIN: https://ranklab-development.eu.auth0.com/
          RANKLAB_S3_BUCKET: ranklab-dev
          RANKLAB_AWS_ACCESS_KEY_ID: ${{ secrets.RANKLAB_AWS_ACCESS_KEY_ID }}
          RANKLAB_AWS_SECRET_KEY: ${{ secrets.RANKLAB_AWS_SECRET_KEY }}
        image: ghcr.io/ranklab-gaming/ranklab-api:latest
        credentials:
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache builds
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/packages/ranklab-web/.next/cache
          key: ${{ runner.os }}-nextjs-build-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-build-cache-
      - name: Add hosts to /etc/hosts
        run: echo "0.0.0.0 ranklab-development" | tee -a /etc/hosts
      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          working-directory: packages/ranklab-web
          record: true
          build: yarn build
          start: yarn start
          wait-on: "http://ranklab-api:8000,http://ranklab-web:3000"
          browser: firefox
          group: "UI - Firefox"
        env:
          NODE_ENV: test
