name: Test and Deploy
on: [push]
env:
  NODE_ENV: test
  NODE_OPTIONS: --max_old_space_size=4096
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  NEXT_PUBLIC_ASSETS_CDN_URL: ${{ secrets.NEXT_PUBLIC_ASSETS_CDN_URL }}
  NEXT_PUBLIC_UPLOADS_CDN_URL: ${{ secrets.NEXT_PUBLIC_UPLOADS_CDN_URL }}
  NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.RANKLAB_SENTRY_DSN }}
  NEXT_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_STRIPE_PUBLISHABLE_KEY }}
  TEST_STRIPE_ACCOUNT_ID: ${{ secrets.TEST_STRIPE_ACCOUNT_ID }}
  TEST_STRIPE_CUSTOMER_ID: ${{ secrets.TEST_STRIPE_CUSTOMER_ID }}
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_ORG_ID }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          scope: "@ranklab-gaming"
      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build
  chrome-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
        ports:
          - "5432:5432"
      ranklab-api:
        env:
          ROCKET_PROFILE: test
          ROCKET_ADDRESS: 0.0.0.0
          RANKLAB_S3_BUCKET: ${{ secrets.RANKLAB_S3_BUCKET }}
          RANKLAB_AWS_ACCESS_KEY_ID: ${{ secrets.RANKLAB_AWS_ACCESS_KEY_ID }}
          RANKLAB_AWS_SECRET_KEY: ${{ secrets.RANKLAB_AWS_SECRET_KEY }}
          RANKLAB_SENTRY_DSN: ${{ secrets.RANKLAB_SENTRY_DSN }}
          RANKLAB_S3_BUCKET_QUEUE: ${{ secrets.RANKLAB_S3_BUCKET_QUEUE }}
          RANKLAB_STRIPE_SECRET: ${{ secrets.RANKLAB_STRIPE_SECRET }}
          RANKLAB_STRIPE_DIRECT_WEBHOOKS_QUEUE: ${{ secrets.RANKLAB_STRIPE_DIRECT_WEBHOOKS_QUEUE }}
          RANKLAB_STRIPE_DIRECT_WEBHOOKS_SECRET: ${{ secrets.RANKLAB_STRIPE_DIRECT_WEBHOOKS_SECRET }}
          RANKLAB_STRIPE_CONNECT_WEBHOOKS_QUEUE: ${{ secrets.RANKLAB_STRIPE_CONNECT_WEBHOOKS_QUEUE }}
          RANKLAB_STRIPE_CONNECT_WEBHOOKS_SECRET: ${{ secrets.RANKLAB_STRIPE_CONNECT_WEBHOOKS_SECRET }}
          RANKLAB_STRIPE_PRODUCT_ID: ${{ secrets.RANKLAB_STRIPE_PRODUCT_ID }}
          RANKLAB_AUTH0_CLIENT_ID: test
          RANKLAB_AUTH0_CLIENT_SECRET: test
        image: ghcr.io/ranklab-gaming/ranklab-api:latest
        credentials:
          username: $
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - "8000:8000"
        options: >-
          --add-host=ranklab-test:host-gateway
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          scope: "@ranklab-gaming"
      - name: Add hosts
        run: echo "127.0.0.1 ranklab-test ranklab-api postgres" | sudo tee -a /etc/hosts
      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build
      - name: Run Chrome tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: apps/ranklab-web
          record: true
          start: npm run test:start
          wait-on: "http://ranklab-api:8000,http://ranklab-test:3000"
          browser: chrome
          group: "Chrome"
          install: false
      - name: Output container logs
        if: ${{ failure() }}
        run: cat /containers/**/*.log
